version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - java -version
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post-build
artifacts:
  files:
    - target/live-class-0.0.1-SNAPSHOT.jar
    - location
    